// <auto-generated />
namespace ManageCase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correctedTypesinRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctedTypesinRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201610131655293_corrected Types in Record"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
